ran_numA = sample(69:99, 25, replace=TRUE)
ran_numB = sample(1:49, 25, replace=TRUE)
matA = matrix(ran_numA, nrow = 5)
matB = matrix(ran_numB, nrow = 5)
cat("Matrix A:\n")
print(matA)
cat("Matrix B:\n")
print(matB)
cat("Multiplication of A and B:\n")
print(matA*matB)
cat("Addition of A and B:\n")
print(matA+matB)
cat("Transpose Matrix A:\n")
tmat = t(matA)
print(tmat)